discordapp/discord-rpc

- src/CMakeLists.txt
I've tested the change on both `clang++` and `g++`. Before this update GCC's implementation could not compile, but with it both `clang++` and `g++` can.
> Change -Weverything to -Wall for more compilers

- examples/unrealstatus/Plugins/discordrpc/Source/ThirdParty/discordrpcLibrary/discordrpcLibrary.Build.cs
UE4 requires the include file from the release zip file to be somewhere, so I suggest making a new folder in \Plugins\discordrpc\Source\ThirdParty\discordrpcLibrary called Include and add it there.
> Add entry for include folder where you have to place discord-rpc.h

- examples/unrealstatus/Plugins/discordrpc/Source/discordrpc/Private/discordrpc.cpp
- examples/unrealstatus/Plugins/discordrpc/Source/discordrpc/Public/DiscordRpcBlueprint.h
- src/backoff.h
- src/connection_win.cpp
- src/discord_register_linux.cpp
- src/discord_register_osx.m
- src/discord_register_win.cpp
- src/serialization.h
The change from `steam://run` to `steam://rungameid` allows to launch mods without a Steam ID (fixes #16); the addition of two lines in `LinearAllocator::Realloc()` fixes an unused argument warning/error when compiling with `CMAKE_BUILD_TYPE=Release` (fixes #17).
The clang-format commit is the changes I got when running cmake for the first time (it clang-formats automatically).
> Fix #16 and #17

- appveyor.yml
A successful Appveyor build: https://ci.appveyor.com/project/judge2020/discord-rpc/build/4
The install script will first download and install cmake 3.8.0, then use it to build as stated in the readme.
Appveyor must first be requested, then approved by the organization owner at https://github.com/organizations/discordapp/settings/oauth_application_policy. Then this repository must be enabled at https://ci.appveyor.com/projects/new by an organization member.
Note: the appveyor URL will be linked to the member who enables it, so if [Chris](https://github.com/crmarsh) enables it the permalink will be `https://ci.appveyor.com/project/crmarsh/discord-rpc`.
> Create Appveyor config for automated CI testing

- CMakeLists.txt
- build.py
- src/CMakeLists.txt
In order to add as a port to [vcpkg](https://github.com/Microsoft/vcpkg), I needed to patch the cmakelists with the following changes:
- Remove forced /MT directive (the CRT depends on debug or release, static or dynamic).
- Allow building for debug by removing the force configuration release.
- Add option to prevent building of example apps.
If these can be merged upstream then I can do away with the diff patch in vcpkg. Thanks.
Related PR: https://github.com/Microsoft/vcpkg/pull/2174
> Improve cmakelists for vcpkg building

- appveyor.yml
I just realized that build.py outputs files in build\install as well as the respected old directories, however, I doubt someone is looking to download the generated cmake files along with the build output.
[build result](https://ci.appveyor.com/project/judge2020/discord-rpc/build/artifacts)
> Change appveyor artifacts

- src/discord_register_win.cpp
As per
https://msdn.microsoft.com/en-us/library/windows/desktop/ms683198(v=vs.85).aspx,
the advised use for getting the file name of a module from `<current
process>` is to use the simplified version. Additionally, this clears
the confusion introduced in Win7's PSAPI which moved
`GetModuleFileNameExW` into the kernel, changing its signature to
`K32GetModuleFileNameExW`, effectively breaking pre-Win7 uses unless
actively mitigated with `#define PSAPI_VERSION 1`
> Use simpler version of GetModuleFileNameW

- README.md
Changes documentation link in readme which currently just leads to a 404.
> Fix broken docs URL

- include/discord-rpc.h
This change fixes a compilation error in case strict prototypes are treated as errors:
```
error: function declaration isn’t a prototype [-Werror=strict-prototypes]
void (*ready)();
```
> make ready() to explicitly take no arguments -> ready(void)

- examples/button-clicker/Assets/DiscordRpc.cs
- examples/send-presence/send-presence.c
- examples/unrealstatus/Plugins/discordrpc/Source/discordrpc/Private/DiscordRpcBlueprint.cpp
- examples/unrealstatus/Plugins/discordrpc/Source/discordrpc/Public/DiscordRpcBlueprint.h
- include/discord-rpc.h
- src/discord-rpc.cpp
- src/serialization.cpp
send-presence example updated - start a line with 'c' to toggle
whether presence information is sent or not.
Added ClearPresence to .cs bindings
Added ClearPresence to UE4 blueprint class.
> add `Discord_ClearPresence()`

- src/discord_register_win.cpp
- src/serialization.h
The first test of my patch provided in issue #102 ended up in a segfault. Turns out strsafe.h substitution was insufficient and could lead to stack corruption. It was caused by a simple lack of size conversion, when wchars in different functions are treated as bytes or as wchars. The aim of this PR is to fix this problem.
* Replaced the StringCbPrintfW macro with a proper function for a size conversion could be provided
* Replaced the only occasion of StringCbCopyW with a StringCbPrintfW call, as it is used elsewhere in this function, so it's buggy substitute function could be safely removed
* Prevented a few possible failures in the RegSetKeyValueW syscall substitute (according to MSDN references)
* Fixed indentation in substitute functions
> Fix segfaults in Discord_RegisterW in MinGW builds

- README.md
- build.py
- examples/button-clicker/Assets/Editor/BuildHelper.cs
Currently, `build.py unity` only creates the libs and does not move them to the right place, and `build.py unreal` does nothing. This PR aims to have the script properly create and move the libs to their proper folders for either target based on operating system.
In the future, the `BuildHelper.cs` script can probably be changed to reference this instead, but it's not currently harmful.
> Update build.py to properly build and copy libraries for Unity and Unreal

- src/serialization.cpp
Currently in the SDK serialization, `partyMax` is an optional field, and one can send a `partySize` without including a max. This will throw an error from discord of:
```
"child "activity" fails because [child "party" fails because [child "size" fails because ["size" must contain 2 items]]]"
```
This PR aims to fix this by making it mandatory to include both `partySize` and `partyMax` if attempting to serialize `party.size`. Rather than throwing an error, the SDK will not write `party.size` to Discord if both fields are missing.
This also fixes #111.
EDIT examples:
Code:
```cs
public void OnClick()
{
Debug.Log("Discord: on click!");
clickCounter++;
DiscordRpc.RichPresence presence = new DiscordRpc.RichPresence();
presence.details = string.Format("Button clicked {0} times", clickCounter); …
```
> Making partyMax required if partySize is included

- src/discord_register_win.cpp
A follow-up to https://github.com/discordapp/discord-rpc/pull/127 which I discovered only a bit later when checking our mingw job.
> Fix mingw compilation with -Werror=missing-declarations

- src/CMakeLists.txt
Required by `RegCreateKeyExW` and others.
> Add advapi32 to linked libraries

- CMakeLists.txt
- README.md
- build.py
- documentation/hard-mode.md
- examples/button-clicker/Assets/DiscordRpc.cs
- examples/send-presence/send-presence.c
- examples/unrealstatus/Plugins/discordrpc/Source/DiscordRpc/Private/DiscordRpcBlueprint.cpp
- include/discord_rpc.h
- src/CMakeLists.txt
- src/discord_rpc.cpp
- src/serialization.cpp
- src/serialization.h
Right now, handlers for events are only updated with an `Discord_Initialize()` call, leading to issues like https://github.com/discordapp/discord-rpc/issues/26#issuecomment-352931913.
This PR aims to allow developers to dynamically register new event handlers more easily/explicitly:
1. **Dynamically Register for Spectate/Join/ATJ events based on handlers bound**
2. **Export `Discord_UpdateHandlers()` into the header file**
A more explicit function call is probably better.
3. **Update C# wrapper to include new function call**
Wew.
I'm not sure if it's better practice to lock the mutex on the whole if block, like I did, or on each callback call in the block, so suggestions welcome there.
> Dynamic Event Handler Registration

- src/msg_queue.h
This avoids a segfault in gcc 4.8:
```
lib/discord/src/msg_queue.h: In instantiation of 'MsgQueue<ElementType, QueueSize>::MsgQueue() [with ElementType = QueuedMessage; long unsigned int QueueSize = 8ul]':
lib/discord/src/discord_rpc.cpp:66:50:   required from here
lib/discord/src/msg_queue.h:16:16: internal compiler error: Segmentation fault
MsgQueue() {}
^
Please submit a full bug report,
with preprocessed source if appropriate.
```
I don't think this will have any different kind of behavior, but please correct me if I'm wrong.
Had to fix this, as we *still* currently require gcc 4.8 for building within the Steam Runtime. (Also see https://github.com/ValveSoftware/steam-runtime/issues/55)
> Syntax change to avoid gcc 4.8 segfaulting

- examples/unrealstatus/Plugins/discordrpc/Source/DiscordRpc/Private/DiscordRpc.cpp
- include/discord_register.h
- src/discord_register_linux.cpp
- src/discord_register_win.cpp
- src/serialization.cpp
- src/serialization.h
It's terribly inconvenient to have clang-format run on each (non-CI) build while the sources are not formatted properly. This applies clang-format rules to prevent re-formatting on each build.
> Apply formatting

- src/discord_rpc.cpp
I ran into an issue where this code didn't work correctly
```cpp
Discord_ClearPresence();
Discord_Shutdown();
```
however doing this, gives the desired behavior.
```cpp
Discord_ClearPresence();
//Discord_Shutdown();
```
This PR will allow for the code above to work correctly.
To give a little context, some users asked me to create an option in the UI to disable Rich Presence because of privacy concerns. So, I added the option and had it shutdown Discord RPC when users chose to disable Rich Presence. However, the presence would be stuck and not change until closing the program.
This all happened 6 days ago and I found a fix as described here in this comment. https://github.com/dolphin-emu/dolphin/pull/6983#issuecomment-393745736
> Fixed issue with Discord RPC not updating presence during shutdown

- src/discord_register_linux.cpp
I'm working on integrating Discord Rich Presence into my game, including using `Discord_Register` to register the launcher instead of the game itself. My development OS is Linux Mint. After reverting back and setting autoRegister to 1 when calling `Discord_Initialize`, something broke in the desktop application that it generates: when I attempted to launch the game from Discord using the 'Spectate' button, a popup appeared:
***Failed to open URI "discord-471xxxxxxxxxxxx348://".***
*The specified location is not supported.*
When I opened up *~/.local/share/applications/discord-471xxxxxxxxxxxx348.desktop*, I saw that there were three garbage characters **fݝ$** appended to the end of the file path:
```
[Desktop Entry]
Name=Game 471xxxxxxxxxxxx348 …
```
> [Linux] Null-terminate output from readlink in Discord_Register.

- src/discord_register_linux.cpp
```
../src/discord_register_linux.cpp: In function ‘void Discord_Register(const char*, const char*)’:
../src/discord_register_linux.cpp:37:31: warning: comparison of integer expressions of different signedness: ‘ssize_t’ {aka ‘long int’} and ‘long unsigned int’ [-Wsign-compare]
if (size <= 0 || size >= sizeof(exePath)) {
~~~~~^~~~~~~~~~~~~~~~~~
```
> Fix mismatched signs in comparison after b44defe

- README.md
*DerelictDiscordRPC* (https://github.com/discordapp/discord-rpc/pull/169) has been *abandoned* and superseded by **[Discord RPC D](https://github.com/voidblaster/discord-rpc-d)**.
The new binding is a static one and doesn't use Derelict anymore. This makes it more versatile - since it's possible to use it alongside other bindings depending on older Derelict versions. Furthermore, this should solve a few other possible problems that could occur with the old one.
Thanks to @WebFreak001 and @Vild for helping me testing this.
Also thanks to you, guys, for your great chat client :slightly_smiling_face:
> Update D binding link: DerelictDiscordRPC has been supersed by Discord RPC D

- .travis.yml
#210 was created under assumption `build.py` is actually used, but upon
inspecting `.travis.yml` it turns out it is not.
> Fix #210: WARNINGS_AS_ERRORS doesn't work

- src/connection_unix.cpp
- src/discord_rpc.cpp
From recv(): The return value will be 0 when the peer has performed an orderly shutdown
This way it should notice that the connection was closed when trying to read, forcing it to try and reconnect automatically instead of on write.
Another issue I've found lies in https://github.com/discordapp/discord-rpc/blob/e32d001809c4aad56cef2a5321b54442d830174f/src/discord_rpc.cpp#L338-L341
Here it changes the handlers to `{}` meaning the `disconnected` handler will not be called, is this intentional?
> Improve handling of disconnects and reconnects

- examples/button-clicker/Assets/DiscordRpc.cs
Using the static Callback methods in the EventHandler which is passed to the Initialize method, which in turn invokes the methods of the static EventHandler "Callbacks".
This way the actual delegates which are called in native code point to static methods. 
Fixes `IL2CPP does not support marshaling delegates that point to instance methods to native code.` in builds.
> Static EventHandler for IL2CPP support
